hackersjail/mugensweeper

.eslintrc.js, .gitignore, .prettierignore, .prettierrc, .vscode/extensions.json, .vscode/settings.json, package.json, yarn.lock
- ESLint, Prettier の設定を Airbnb を基準に更新
- Visual Studio Code の共有設定を追加
=> Add utilities

.circleci/config.yml, .eslintrc.js, .prettierrc, .vscode/settings.json, LICENSE, api/config.js, api/database.js, api/docs/dev/Example.yml, api/jest.config.js, api/models/ExampleModel.js, api/nodemon.json, api/routes/app.js, api/routes/dev/example.js, api/routes/dev/index.js, api/server.js, api/swagger.js, api/tests/routes/dev/example.test.js, api/tests/setup.js, package.json, yarn.lock
`api/` に API 関連のファイルを追加
1.  Jest を使用したテストフローの追加
2.  API の Server は Express を使用
3.  データベースは MongoDB を使用
- Mongoose を使用して JavaScript から操作
- 環境変数として `MONGO_URI` を用意し一旦 MongoDB Atlas の環境を利用して動作確認
4.  API のドキュメントは Swagger を使用
5.  CircleCI の設定追加
=> Add API server scripts

api/routes/dev/eto/field.js, api/routes/dev/index.js, api/tests/routes/dev/eto/field.test.js
=> フィールドAPIのテスト

.circleci/config.yml, README.md, package.json
CircleCI, pre-commit hook で ESLint の設定漏れを修正しました。
=> Fix ESLint workflow

api/routes/dev/index.js, api/routes/dev/rennie/field.js, api/tests/routes/dev/rennie/field.test.js
一回目のプルリク送ります。よろしくお願いします。きちんと送れてることを祈ります。
=> field apiのテストまで完了

api/routes/dev/index.js, api/routes/dev/mishima/field.js, api/tests/routes/dev/mishima/field.test.js
./mugensweeper/api/routes/dev/index.js
上記ファイルのコンフリクトを解消しました。
=> index.js修正

.circleci/config.yml, api/tests/routes/dev/example.test.js
- CircleCI の設定ファイルを更新
- #18 で Jest のエラーが発生していた MongoDB のテストファイルを復元
- CircleCI に SSH でログインしたところ `~/.mongodb-binaries` が存在しなかったので、削除コマンドは追加せず様子見
=> Update CircleCI configuration

api/database.js
Mongoose を使用した MongoDB への接続周りの記述を整理しました。
=> Update MongoDB settings

api/routes/dev/miyamoto/block.js, api/tests/routes/dev/miyamoto/block.test.js
宮本です。
重複排除テストの実ロジック作成しましたので、
ご確認よろしくお願いいたします。
=> 重複排除テストの実ロジック作成しました（swagger追記不要・テスト確認済）

api/models/dev/miyamoto/FieldModel.js, api/models/dev/miyamoto/fieldStore.js, api/tests/routes/dev/miyamoto/block.test.js, api/tests/routes/dev/miyamoto/field.test.js
宮本です。
miyamotoFieldModelが誕生しましたので、ご対応よろしくお願いいたします。
=> miyamotoFieldModelが誕生しました

api/routes/app.js, api/routes/v1/index.js, api/routes/v1/user/user.js, api/tests/routes/v1/user/user.test.js
#105 のAPIテストの修正版です。よろしくお願いします。
=> 105のテスト作成修正１

api/models/dev/mishima/FieldModel.js
なし（v0の変更）
- Fieldモデルの名前を一意となるように変更しました。
　（FieldModel→MishimaFieldModel）
なし
なし
=> v0開発）モデル名を一意になるように変更

.circleci/config.yml
なし
- CircleCI 上で Node.js のバージョンを指定（Current v11）してテストを実行する `npx` コマンドを追加
- Yarn による脆弱性診断を追加
なし
なし
=> Add run script in CircleCI

.circleci/config.yml, api/routes/app.js, components/UserNameInput.vue, nuxt.config.js, package.json, pages/index.vue, plugins/axios.js, store/index.js, yarn.lock
#143 
- 三島さんVuex活用のためstore/index.jsのみプルリク実施
無し
無し
=>  三島さんVuex活用のためstore/index.jsのみプルリク実施

api/routes/v1/field/field.js, api/routes/v1/index.js, api/tests/routes/v1/field/field.test.js
fieldHistoryに打ち手を追加するテスト、実装を追加しました。
=> added response test to field.test.js

package.json
nodemon の Windows へのエラーを修正しました。
- なにを、どう、変更したか
- 複雑なアルゴリズムの説明
- 参考にしたリソース
- チケット
- ...
=> fixed error

api/routes/v1/util/judgeExploded.js, api/tests/routes/v1/util/judgeExploded.test.js
#201 
開かれたblockとBomMapを照らし合わせexplodeを含む配列を生成する関数の製成とテストを作成しました。
よろしくお願いします。
=> 開かれたblockとBomMapを照らし合わせexplodeを含む配列を生成する

api/routes/v1/bom/countBoms.js, api/tests/routes/v1/bom/countBoms.test.js
#212 
周囲8マスのBomの数を返すテストと実装を追加しました。
=> added countBoms

api/models/v1/BomHistoryModel.js, api/models/v1/bomStore.js, api/routes/v1/bom/createPartOfBoms.js, api/server.js, api/tests/routes/v1/bom/bomStore.test.js
#147 
bomHistoryを追加しました。
- なにを、どう、変更したか
- 複雑なアルゴリズムの説明
- 参考にしたリソース
- チケット
- ...
=> added bomHistory

components/Ranking.vue, nuxt.config.js, package.json, pages/index.vue, plugins/vue-touch.js, store/index.js
#215 
- 盤面をドラッグする事で、初期表示領域外へも盤面情報を移動可能としました。
コードが松田さん基準の記述になっているか否か。
無し
=> 盤面の表示領域を無限化し、表示領域外への移動を可能とするよう改修しました。

deploy.sh, package.json, process.json, yarn.lock
なし
AWS CodeDeploy の対応のため PM2 を追加しました。
なし
なし
=> Add process manager

api/models/dev/miyamoto/fieldStore.js, pages/index.vue
#193
- 開いたblock上の周囲に爆弾が埋まっている個数を表示しました。
ソースが松田さんの記述水準に達しているか否か。
無し
=> 開いたblock上の周囲に爆弾が埋まっている個数を表示しました。

api/models/v1/FieldHistoryModel.js, api/models/v1/fieldStore.js, api/routes/v1/field/field.js, api/routes/v1/field/post2res.js, api/routes/v1/util/judgeField.js, api/tests/routes/v1/field/field.test.js
=> フロントにbomCount、explodedを返すテスト、実装の追加

pages/index.vue
#230 
- 開いたblockについて、盤面の表示領域をドラッグして移動させようとする際に生じる盤面との誤差を改修
修正による悪影響の可能性がないかについて。
無し
=> 開いたblockについて、盤面の表示領域をドラッグして移動させようとする際に生じる盤面との誤差を改修しました。

package.json, process.json
なし
AWS CodeDeploy で別プロジェクトと干渉していた PM2 の  `app.name` を修正しました。
なし
なし
=> Fix app name in PM2

nuxt.config.js
=> Clear default comment

api/routes/v1/util/judgeField.js
judgeFieldを修正しました
- なにを、どう、変更したか
- 複雑なアルゴリズムの説明
- 参考にしたリソース
- チケット
- ...
=> modified judgeField

api/docs/v1/field.yml
swaggerのymlファイルについてreturn値のtypeが違っていたので修正しました。
=> correctTypeErr

api/routes/v1/bom/createPartOfBoms.js
=> modified createPartOfBoms2

api/tests/routes/v1/field/field.test.js, api/tests/routes/v1/util/array2bomMap.js, api/tests/routes/v1/util/array2fieldHistory.js, api/tests/routes/v1/util/judgeExploded.test.js, api/tests/routes/v1/util/point.test.js
イシューハントなのでありません。
- なにを、どう、変更したか
・field.test.jsのarray2fieldHistoryに渡すパラメータを可読性を上げるため、かつばらつきがあったため修正
・上記のarray2fieldHistoryに渡すパラメータ変更に伴いロジックを修正。ついでにリファクタリング
・point.test.jsとjudgeExploded.test.jsでもarray2fieldHistoryを利用していたため、こちらもパラメータを修正
・またpoint.test.jsとjudgeExploded.test.jsの中で、爆弾の配置を管理するbommapもarray2fieldHistoryを利用して変換しており、弊害がありそうだったので、array2bomMapを追加しそちらで変換するように修正
追加したのは、array2bomMapのみです。
- 複雑なアルゴリズムの説明
とくにありません。
各テストの可読性と、
array2fieldHistory.js、array2bomMap.jsのロジックが問題ないか確認いただければ助かります。
- 参考にしたリソース
- チケット
- ...
=> テストで利用する関数array2fieldHistoryのロジック変更に伴い、関連するテストファイルのロジックを修正しました

api/routes/v1/util/judgeField.js
=> returnの箇所について、ソースを簡易化しました。

api/routes/v1/util/judgeExploded.js
=> modified judgeExploded

api/routes/v1/field/post2res.js
userIdを追加しました。
rankingを作成するのにuserIdが必要なため
- 参考にしたリソース
- チケット
- ...
=> userId 追加 no2

api/models/v1/pointStore.js
=> modified pointStore

api/routes/v1/authentication/generateAccessToken.js
=> modified generateAccessToken

api/models/v1/pointStore.js, api/routes/v1/authentication/auth.js, api/routes/v1/authentication/generateAccessToken.js
pointStore.js と generateAccessToken.js を簡略化しました
=> issue hunt

api/models/v1/fieldStore.js, api/routes/v1/util/judgeField.js
=> ソースを修正しました。

api/models/v1/userStore.js, api/routes/v1/authentication/generateAccessToken.js
=> modified userStore.js

api/routes/v1/bomb/createPartOfBombs.js
=> modified　createPartOfBombs.js

.circleci/config.yml, .circleci/webhook.sh
なし
静的ファイルの展開先を Amazon S3 から Netlify に変更するにあたって CircleCI で不要になった記述を削除しました。
なし
なし
=> Delete deployment workflow for Web

api/routes/v1/bomb/createPartOfBombs.js
createPartOfBoms の返り値が返っていなかったため修正しました。
=> modified createPartOfBoms

api/routes/v1/bomb/countBombs.js
countBombs.js より directionsを消去しました。
- なにを、どう、変更したか
- 複雑なアルゴリズムの説明
- 参考にしたリソース
- チケット
- ...
=> modified countBombs

api/routes/v1/util/judgeField.js
=> refacter judgeField.js

api/models/v1/pointStore.js, api/routes/v1/util/generateRankingWithUserNames.js, api/tests/routes/v1/util/generateRankingWithUserNames.test.js, api/tests/routes/v1/util/point.test.js
#307 
user名を含んだランキングを生成する関数を作成しました。
この関数を使用して、先日出したプルルク「pointの部分router」を完成させたいと思います。
よろしくお願いします。
- なにを、どう、変更したか
- 複雑なアルゴリズムの説明
- 参考にしたリソース
- チケット
- ...
=> ランキング作成に必要な関数の作成

components/Ranking.vue
#182
- ランキングコンポーネントのstyleを修正
なし
=> renovate issue#182 (change style of Ranking Compornents)

api/routes/v1/authentication/generateAccessToken.js
generateAccessToken.jsを簡略化しました。
=> generateAccessToken.jsを簡略化しました。

store/index.js
#191
- リクエストボディからユーザーIDを削除しました。
=> renovate issue#191 (delete propaties(userId) from request body)

api/server.js
=> node issue

api/server.js
initData、initBombの読み込みの順番を変更しました。
=> modified order of initData

package.json
なし
`npm version prerelease` で `package.json` のバージョンアップ
なし
なし
=> Pre-release v0.0.1-0

api/models/v1/userStore.js
Reverts hackersjail/mugensweeper#333
=> Revert "新規データベースでユーザーを作成した際userIdが空のレスポンスになるバグを修正しました。"

pages/index.vue
=> added explode effect

pages/index.vue
=> fixed image sizeing

pages/index.vue
=> added click action

components/Ranking.vue, pages/index.vue, store/index.js, utils/calcDistance.js
- スマホでのズーム
- ブロック上でもイベントを取得できるようにした
- 参考にしたリソース
- チケット
- ...
=> スマホでのズーム対応

store/index.js
=> refactoring

pages/index.vue
なし
本番、ステージング環境で発生していたユーザー登録時のエラーを修正しました。
1.  本番、ステージング環境のどちらかをシークレットモードで開く
- https://mugensweeper.netlify.com/
- https://stg-mugensweeper.netlify.com/
2.  ユーザー名を入力し登録をクリックするとスタートの表示にリダイレクトする
Vuex `actions` に登録されている `getAccessToken` 関数が Promise を返しているものの、呼び出している `pages/index.vue` の `registerName` 関数の中は `await` されていないため
なし
なし
=> Fix asynchronous function
